---
title: "College Analysis"
author: "Tyler Wilson"
date: "8/8/2020"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
tuition_cost <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_cost.csv')

tuition_income <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/tuition_income.csv') 

salary_potential <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/salary_potential.csv')

historical_tuition <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/historical_tuition.csv')

diversity_school <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-10/diversity_school.csv')
```

```{r}
tuition_cost <- tuition_cost %>% 
  mutate_if(is_character, as_factor)

tuition_cost %>% 
  summary()
```

```{r}
tuition_cost %>% 
 filter(degree_length == 'Other')


```

